#!/bin/sh
#
#qubilities:qupull
#Copyright (C) 2017  saces@c-base.org
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program. If not, see <http://www.gnu.org/licenses/>.

source ./.quconfig

rm -r ~/QubesIncoming/${QU_PUSHPULL_VM}/${QU_PUSHPULL_PATH}

mkdir -p ~/QubesIncoming/${QU_PUSHPULL_VM}/${QU_PUSHPULL_PATH}

qvm-run --pass-io Devel1 "tar -cf - -C ${QU_PUSHPULL_VM_PATH} ." | tar -xf - -C ${QU_PUSHPULL_DOM0_PATH}
